FROM node:22-bookworm
WORKDIR /peerBench

# Copy package.json files
COPY package*.json .
COPY apps/pigeon/package*.json ./apps/pigeon/
COPY packages/sdk/package*.json ./packages/sdk/

# Install dependencies
RUN npm ci

# Copy source code
COPY apps/pigeon ./apps/pigeon
COPY packages/sdk ./packages/sdk

# TODO: Use turborepo to do that
# Build the projects
RUN cd packages/sdk && npm run build && cd ../..
RUN cd apps/pigeon && npm run build && cd ../..

CMD ["node", "apps/pigeon/dist/index.js"]