/**
 * Simulation Types
 *
 * Extends the original simulation system with realistic user generation
 * and database persistence capabilities.
 */

// ============================================================================
// Core Persona Types (from original simulation)
// ============================================================================

export type PersonaType = 'altruistic' | 'greedy' | 'cabal' | 'random' | 'malicious';

export interface Feedback {
  id: string;
  userId: string;
  promptId: string;
  opinion: 'positive' | 'negative';
}

// ============================================================================
// Simulation Mode Configuration
// ============================================================================

export interface SimulationMode {
  /**
   * If true, use realistic personas generated by LLM
   * If false, use simple persona types (altruistic, greedy, etc.)
   */
  realistic_people: boolean;

  /**
   * If true, only generate data in memory (no DB writes)
   * If false, data can be written to DB based on write_to_db flag
   */
  in_memory_only: boolean;

  /**
   * If true, write generated data to the database
   * Only applies when in_memory_only is false
   */
  write_to_db: boolean;
}

// ============================================================================
// Simple Simulation Config (for in-memory simulations)
// ============================================================================

export interface SimpleSimulationConfig extends SimulationMode {
  numUsers: number;
  personas: {
    altruistic: number;    // percentage (0-100)
    greedy: number;
    cabal: number;
    random: number;
    malicious: number;
  };
  numPromptsPerUser: {
    min: number;
    max: number;
  };
  probabilityReview: number;           // 0-1, probability a user reviews a prompt
  probabilityMultipleReviews: number;  // 0-1, probability a prompt gets multiple reviews
  percentageGoodPrompts: number;       // 0-100, percentage of prompts that are "good quality"
  cabalSize: number;                   // How many users per cabal group
}

// ============================================================================
// Realistic Simulation Config (for LLM-generated personas)
// ============================================================================

export interface RealisticPersonality {
  name: string;
  background: string;
  interests: string[];
  behaviorTraits: string[];
  reviewStyle: string;
  promptCreationStyle: string;
}

export interface RealisticBenchmarkIdea {
  theme: string;
  description: string;
  targetDomain: string;
  promptCount: number;
}

export interface RealisticSimulationConfig extends SimulationMode {
  numUsers: number;
  orgDomains?: string[];  // Optional: limit to specific org domains
  countries?: string[];   // Optional: limit to specific countries
  llmModel?: string;      // Default: gemini-flash-2.0
  promptsPerUser: {
    min: number;
    max: number;
  };
  // Prompt set options
  createPromptSets?: boolean;     // Whether to create new prompt sets
  promptSetsPublic?: boolean;     // Make prompt sets public
  submitToExisting?: boolean;     // Submit to existing prompt sets instead
  promptType?: 'multiple_choice' | 'open_ended' | 'random';  // Type of prompts to generate
  // Custom system prompts for LLM generation
  customPrompts?: {
    personalitySystem?: string;    // System prompt for personality generation
    benchmarkSystem?: string;      // System prompt for benchmark idea generation
    promptSystem?: string;         // System prompt for test prompt generation
  };
}

// ============================================================================
// Unified Simulation Config
// ============================================================================

export type SimulationConfig = SimpleSimulationConfig | RealisticSimulationConfig;

// ============================================================================
// Simulated User Types
// ============================================================================

export interface SimpleSimulatedUser {
  id: string;
  displayName: string;
  email?: string;
  hasAffiliation: boolean;
  persona: PersonaType;
  cabalId?: string;
  metadata?: {
    isSimulated: true;
    simulationType: 'simple';
  };
}

export interface RealisticSimulatedUser {
  id: string;
  displayName: string;
  email: string;
  orgDomain: string;
  orgId?: number;
  orgName?: string;
  orgCountry?: string | null;
  personality: RealisticPersonality;
  benchmarkIdea: RealisticBenchmarkIdea;
  hasAffiliation: boolean;
  metadata: {
    isSimulated: true;
    simulationType: 'realistic';
    personality: RealisticPersonality;
    benchmarkIdea: RealisticBenchmarkIdea;
    orgName?: string;
    orgCountry?: string | null;
  };
}

export type SimulatedUser = SimpleSimulatedUser | RealisticSimulatedUser;

// ============================================================================
// Simulated Prompt Types
// ============================================================================

export interface SimpleSimulatedPrompt {
  id: string;
  creatorId: string;
  question: string;
  isGoodQuality: boolean;
  type: 'simple';
}

export interface RealisticSimulatedPrompt {
  id: string;
  creatorId: string;
  question: string;
  fullPrompt: string;
  answerKey?: string;
  metadata: {
    generatedByLLM: true;
    benchmarkTheme: string;
    promptType: 'multiple_choice' | 'open_ended';
  };
  type: 'realistic';
}

export type SimulatedPrompt = SimpleSimulatedPrompt | RealisticSimulatedPrompt;

// ============================================================================
// Simulation Results
// ============================================================================

export interface SimulatedData {
  users: SimulatedUser[];
  prompts: SimulatedPrompt[];
  feedbacks: Feedback[];
  config: SimulationConfig;
  generatedAt: Date;
  dbWritten?: boolean;
}

// ============================================================================
// Default Configurations
// ============================================================================

export const DEFAULT_SIMPLE_SIMULATION_CONFIG: SimpleSimulationConfig = {
  realistic_people: false,
  in_memory_only: true,
  write_to_db: false,
  numUsers: 50,
  personas: {
    altruistic: 40,
    greedy: 20,
    cabal: 20,
    random: 15,
    malicious: 5,
  },
  numPromptsPerUser: {
    min: 2,
    max: 8,
  },
  probabilityReview: 0.3,
  probabilityMultipleReviews: 0.6,
  percentageGoodPrompts: 60,
  cabalSize: 5,
};

export const DEFAULT_REALISTIC_SIMULATION_CONFIG: RealisticSimulationConfig = {
  realistic_people: true,
  in_memory_only: false,
  write_to_db: true,
  numUsers: 10,
  llmModel: 'google/gemini-2.0-flash-001',
  promptsPerUser: {
    min: 3,
    max: 5,
  },
  createPromptSets: true,
  promptSetsPublic: true,
  submitToExisting: false,
  promptType: 'random',
  countries: ['United States', 'United Kingdom', 'Germany', 'Poland', 'Turkey', 'Switzerland'],
};
